import React, {Fragment} from "react"
import Navbar from "layouts/Navbar"
import Footer from "components/Footers/AdminFooter"
const About = () =>{

    return (
        <Fragment>
            <Navbar/>
        <div className="container-fluid">
            <div className="row">
                <div className="col-xs-12 col-md-12 col-lg-9 center">
                    <div className="card well mt-5">
                        <h1 className="text-center mt-3">FREQUENTLY ASKED QUESTIONS</h1> <hr/>
                        <div className="col-xs-12 col-md-9 col-lg-9 center" >
                                <h2 className="text-center text-primary mt-3">What are the Proinvest Company's activities?</h2>
                                <h3 className="text-center">
                                Proinvest is engaged in trading activities on the on the crypto-currency market. 
                                The company's income is generated by successfully 
                                executed trades on the currency market.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Why does the company attract additional investments from private individuals?</h2>
                                <h3 className="text-center">
                                Additional investments will allow to increase the number of 
                                transactions executed on the currency market, and thus will increase the overall profitability of the company. 
                                Investors in turn will receive certain percentage of profit
                                 depending on the amount of funds invested.
                                </h3> <hr/>

                                <h2 className="text-center text-primary mt-3">What are the advantages of the Proinvest Company over competitors?</h2>
                                <h3 className="text-center">
                                 Our goal is not to conduct the tough competition, but to receive a stable
                                 profit on the crypto-currency market using our own strategy. We have developed special investment
                                 packages with optimum service plans and affiliate program for passive income for investors.
                                </h3> <hr/>

                                <h2 className="text-center text-primary mt-3">What are the risks for Proinvest company's investors?</h2>
                                <h3 className="text-center">
                                The risks for our investors are minimized due to the professional team and our experience.
                                Each company's investor will receive a daily profit according to the terms of the investment plan that was chosen.
                                </h3> <hr/>

                                <h2 className="text-center text-primary mt-3">What do I need in order to start?</h2>
                                <h3 className="text-center">
                                First, you should register on our web-site. The registration procedure is simple 
                                and will take just a few minutes. Fill all required fields in
                                 registration form, login to account, choose an optimum investment plan and deposit your account. After that you'll become
                                 an official investor of the Proinvest Company and will receive a profit according to the service plan chosen.
                                </h3> <hr/>

                                <h2 className="text-center text-primary mt-3">Am I able to create multiple accounts on the web-site?</h2>
                                <h3 className="text-center">
                                No, the multiple registrations on the web-site are forbidden. A single user can create only one account.
                                </h3>  <hr/>

                                <h2 className="text-center text-primary mt-3">Do I need to pass the identity authentication 
                                procedure after the registration on the web-site?</h2>
                                <h3 className="text-center">
                                No, the identity authentication is not required. However,
                                 we are looking for you consciousness and believe that you will provide authentic information about yourself.
                                </h3> <hr/>

                                <h2 className="text-center text-primary mt-3">Can I change my personal data (login, password, e-mail etc.)?</h2>
                                <h3 className="text-center">
                                Yes, you can change some of your personal data through the personal account by yourself.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">I forgot my account's password. What do I need to do?</h2>
                                <h3 className="text-center">
                                You can recover a password using the automatic password recovery. You can also contact support.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">What is the security level of the company's web-site?</h2>
                                <h3 className="text-center">We use an expensive dedicated server of the ddos-guard.net company which protects our web-site from any DDoS attack. Web-site is also provided
                                with SSL Comodo - the high reliability certificate that provides the higher level of protection and security accreditation.</h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">How to deposit an account?</h2>
                                <h3 className="text-center">
                                Once you make a decision about deposit amount, please, use one of the payment systems which cooperate with the company.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">What payment systems cooperate with the company?</h2>
                                <h3 className="text-center">
                                We cooperate with Perfect Money, Payeer, AdvCash, Bitcoin, Litecoin, Ethereum, Bitcoin Cash and Dash.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">What is the basis of profit charging?</h2>
                                <h3 className="text-center">
                                Profit will be charged on your personal account according to the investment plan that was chosen.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">What is the minimum and maximum deposit amount?</h2>
                                <h3 className="text-center">
                                The minimum deposit amount is $100. Maximum - unlimited.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">What is the minimum withdrawal amount?</h2>
                                <h3 className="text-center">
                                The minimum withdrawal amount is $100
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Am I able to create several deposits
                                 at a time and make profit from two investment plans simultaneously?</h2>
                                <h3 className="text-center">
                                Yes, you can place money on any number of deposits with a single account and make profit from multiple investment plans.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Is it possible to place money using one payment system and withdraw them using another?</h2>
                                <h3 className="text-center">
                                No, you can withdraw money only with the payment system that was used to place them on deposit.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Am I able to request the deposit withdrawal before the end of investment period?</h2>
                                <h3 className="text-center">
                                No. The deposit can be withdrawn only after the end of investment period which is specified in the investment plan that was chosen.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">How quickly can the request of the money withdrawal be processed?</h2>
                                <h3 className="text-center">
                                The request is processed in manual mode for 24 business hours (3 working days).
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Do you have any hidden fees for money deposit/withdrawal?</h2>
                                <h3 className="text-center">
                                No, we don't have any hidden fees. Withdraw fee Bitcoin - 0.0005 BTC ($4)
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">What are the characteristics of the deposits crediting in the crypto-currency system?</h2>
                                <h3 className="text-center">
                                Bitcoin, Bnb, Ethereum, Bitcoin Cash and Dash, being a decentralized system, 
                                carries out transactions on the basis of a certain number of confirmations in the
                                 blockchain network, which are required so that the transaction was considered complete.
                                  Deposits in the Proinvest made
                                 via crypto-currency system, require a minimum of 2 confirmations before being recorded 
                                 in the personal account of the investor.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Is the fixed rate of Bitcoin against the dollar being used by the Proinvest company?</h2>
                                <h3 className="text-center">
                                Yes, to minimize effects from the volatility of the exchange rate of Bitcoin 
                                for our clients, we use a fixed rate determined at $8000/BTC. 
                                All deposits in Bitcoin by the clients Proinvest, are automatically converted at this rate.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Do you have an affiliate program?</h2>
                                <h3 className="text-center">
                                Yes, we developed a single-level affiliate program according to which a
                                 program beneficiary will be charged with 5% of commission charge from the each of his/her partner deposit amounts.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">How can I use money which was gained via the affiliate program participation?</h2>
                                <h3 className="text-center">
                                You can withdraw them or use to invest in a project.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">How can I attract new partners?</h2>
                                <h3 className="text-center">
                                You can use special promotional materials to attract partners.
                                </h3>
                                <hr/>

                                <h2 className="text-center text-primary mt-3">Do you pay a referral commission for a deposit from a balance account?</h2>
                                <h3 className="text-center">
                                No. You receive referral commission only for deposits from payment systems.
                                </h3>
                                <hr/>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <Footer/>
        </Fragment>
    )
}

export default About